
export const ALLPOKEMONS = "ALLPOKEMONS";
export const CLEARPOKEMONS = "CLEARPOKEMONS";
export const DETALLEPOKEMONS = "DETALLEPOKEMONS";
export const CLEARDETALLES = "CLEARDETALLES"
export const SEARCH = "SEARCH"
export const HIDELANDING = "HIDELANDING"
export const SHOWLANDING = "SHOWLANDING"
export const ALLTYPE = "ALLTYPE";
export const FILTERTIPOS = "FILTERTIPOS"