
export const ALLPOKEMONS = "ALLPOKEMONS";
export const CLEARPOKEMONS = "CLEARPOKEMONS";
export const DETALLEPOKEMONS = "DETALLEPOKEMONS";
export const CLEARDETALLES = "CLEARDETALLES"
export const SEARCH = "SEARCH"